version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db_shopbillbuddy
    environment:
      POSTGRES_DB: shopbillbuddy
      POSTGRES_USER: shopbillbuddy_user
      POSTGRES_PASSWORD: shopbillbuddy_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: